<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.1.1.1</AssemblyVersion>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccMutationsProcessor\AccMutationsProcessor.csproj" />
    <ProjectReference Include="..\AccountsDataCache\AccountsDataCache.csproj" />
    <ProjectReference Include="..\CoreDTO\CoreDTO.csproj" />
  </ItemGroup>

</Project>
